language: android
branches:
  only:
    - master
    - develop

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

script:
  - ./gradlew :retroauth-core:build :retroauth-android:build

after_failure: "cat /home/travis/build/andretietz/retroauth/retroauth-android/build/outputs/lint-results-debug.xml"