name: Release build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Version Check
        run: |
          version=$(grep "VERSION_NAME" gradle.properties | cut -d'=' -f2 )
          if [[ $version != *"-SNAPSHOT"* ]]; then
            echo "Version string MUST contain \"-SNAPSHOT\"!"
            exit 1;
          fi
          version=$(grep "VERSION_NAME" "./gradle.properties"|cut -d'=' -f2| sed 's/-SNAPSHOT//g')
          sed -i'' "s/VERSION_NAME=.*-SNAPSHOT/VERSION_NAME=$version/g" gradle.properties
          echo "Building Release Version: $version"

      - name: Build, upload and release Base Version
        run: |
          ./gradlew retroauth:uploadArchives --stacktrace --no-daemon --no-parallel --warning-mode all
          ./gradlew closeAndReleaseRepository --no-daemon --no-parallel --warning-mode all
        env:
          ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_KEY_SECRET }}

      - name: Build, upload and release Android Version
        run: |
          ./gradlew android-accountmanager:uploadArchives --stacktrace --no-daemon --no-parallel --warning-mode all
          ./gradlew closeAndReleaseRepository --no-daemon --no-parallel --warning-mode all
        env:
          ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_KEY_SECRET }}

